SI: config.c data_am.c data_record.c lock.c lock_record.c main.c mem.c proc.c snapshot.c thread_global.c thread_main.c timestamp.c trans.c transactions.c util.c
	gcc -o SI config.c data_am.c data_record.c lock.c lock_record.c main.c mem.c proc.c snapshot.c thread_global.c thread_main.c timestamp.c trans.c transactions.c util.c -lpthread
